# Generated by Django 2.2.7 on 2020-03-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0003_auto_20200316_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyFacesHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileField', models.FileField(upload_to='FriendlyFaces/')),
                ('Name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
