# Generated by Django 2.2.7 on 2020-03-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0004_friendlyfaceshandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistoryHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileField', models.FileField(upload_to='AccessFaces/')),
                ('UpladTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
