# Generated by Django 2.2.7 on 2020-04-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0005_accesshistoryhandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettingsHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('smsnumber', models.TextField()),
                ('houseaddress', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
