# Generated by Django 2.2.7 on 2020-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0006_usersettingshandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToggleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strangernotifications', models.BooleanField()),
                ('authorizednotifications', models.BooleanField()),
                ('receivesms', models.BooleanField()),
                ('receiveemail', models.BooleanField()),
                ('user', models.TextField()),
            ],
        ),
    ]
