# Generated by Django 2.2.7 on 2020-04-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0007_usertogglesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingUtilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileField', models.FileField(upload_to='LoggingUtilities/')),
                ('EventTime', models.DateTimeField()),
                ('AccessType', models.TextField()),
            ],
        ),
    ]
